# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1278, 723)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_1 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_1.sizePolicy().hasHeightForWidth())
        self.frame_1.setSizePolicy(sizePolicy)
        self.frame_1.setMinimumSize(QtCore.QSize(450, 480))
        self.frame_1.setMaximumSize(QtCore.QSize(450, 1000))
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.label_messages = QtWidgets.QLabel(self.frame_1)
        self.label_messages.setGeometry(QtCore.QRect(10, 580, 431, 61))
        self.label_messages.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_messages.setText("")
        self.label_messages.setWordWrap(True)
        self.label_messages.setObjectName("label_messages")
        self.label_10 = QtWidgets.QLabel(self.frame_1)
        self.label_10.setGeometry(QtCore.QRect(10, 560, 81, 16))
        self.label_10.setObjectName("label_10")
        self.label_acquisition_progress = QtWidgets.QLabel(self.frame_1)
        self.label_acquisition_progress.setGeometry(QtCore.QRect(280, 110, 101, 16))
        self.label_acquisition_progress.setText("")
        self.label_acquisition_progress.setObjectName("label_acquisition_progress")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_1)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 440, 551))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName("tabWidget")
        self.SEM = QtWidgets.QWidget()
        self.SEM.setObjectName("SEM")
        self.pushButton_acquire = QtWidgets.QPushButton(self.SEM)
        self.pushButton_acquire.setGeometry(QtCore.QRect(310, 10, 101, 81))
        self.pushButton_acquire.setObjectName("pushButton_acquire")
        self.label_3 = QtWidgets.QLabel(self.SEM)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 161, 20))
        self.label_3.setObjectName("label_3")
        self.comboBox_detector = QtWidgets.QComboBox(self.SEM)
        self.comboBox_detector.setGeometry(QtCore.QRect(10, 140, 71, 22))
        self.comboBox_detector.setObjectName("comboBox_detector")
        self.comboBox_detector.addItem("")
        self.comboBox_detector.addItem("")
        self.comboBox_detector.addItem("")
        self.label = QtWidgets.QLabel(self.SEM)
        self.label.setGeometry(QtCore.QRect(10, 120, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.SEM)
        self.label_2.setGeometry(QtCore.QRect(100, 120, 111, 16))
        self.label_2.setObjectName("label_2")
        self.spinBox_horizontal_field_width = QtWidgets.QDoubleSpinBox(self.SEM)
        self.spinBox_horizontal_field_width.setGeometry(QtCore.QRect(10, 90, 81, 22))
        self.spinBox_horizontal_field_width.setMaximum(10000000.0)
        self.spinBox_horizontal_field_width.setProperty("value", 80.0)
        self.spinBox_horizontal_field_width.setObjectName("spinBox_horizontal_field_width")
        self.spinBox_dwell_time = QtWidgets.QDoubleSpinBox(self.SEM)
        self.spinBox_dwell_time.setGeometry(QtCore.QRect(100, 140, 81, 22))
        self.spinBox_dwell_time.setMaximum(10000000.0)
        self.spinBox_dwell_time.setProperty("value", 1.0)
        self.spinBox_dwell_time.setObjectName("spinBox_dwell_time")
        self.pushButton_select_directory = QtWidgets.QPushButton(self.SEM)
        self.pushButton_select_directory.setGeometry(QtCore.QRect(299, 100, 121, 28))
        self.pushButton_select_directory.setObjectName("pushButton_select_directory")
        self.comboBox_resolution = QtWidgets.QComboBox(self.SEM)
        self.comboBox_resolution.setGeometry(QtCore.QRect(10, 40, 91, 22))
        self.comboBox_resolution.setObjectName("comboBox_resolution")
        self.comboBox_resolution.addItem("")
        self.comboBox_resolution.addItem("")
        self.comboBox_resolution.addItem("")
        self.comboBox_resolution.addItem("")
        self.comboBox_resolution.addItem("")
        self.comboBox_resolution.addItem("")
        self.comboBox_resolution.addItem("")
        self.label_28 = QtWidgets.QLabel(self.SEM)
        self.label_28.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_28.setObjectName("label_28")
        self.checkBox_autocontrast = QtWidgets.QCheckBox(self.SEM)
        self.checkBox_autocontrast.setGeometry(QtCore.QRect(110, 30, 111, 20))
        self.checkBox_autocontrast.setChecked(True)
        self.checkBox_autocontrast.setObjectName("checkBox_autocontrast")
        self.pushButton_last_image = QtWidgets.QPushButton(self.SEM)
        self.pushButton_last_image.setGeometry(QtCore.QRect(310, 140, 101, 81))
        self.pushButton_last_image.setObjectName("pushButton_last_image")
        self.checkBox_save_image = QtWidgets.QCheckBox(self.SEM)
        self.checkBox_save_image.setGeometry(QtCore.QRect(110, 50, 111, 20))
        self.checkBox_save_image.setChecked(True)
        self.checkBox_save_image.setObjectName("checkBox_save_image")
        self.comboBox_beam_type = QtWidgets.QComboBox(self.SEM)
        self.comboBox_beam_type.setGeometry(QtCore.QRect(220, 50, 81, 22))
        self.comboBox_beam_type.setObjectName("comboBox_beam_type")
        self.comboBox_beam_type.addItem("")
        self.comboBox_beam_type.addItem("")
        self.label_4 = QtWidgets.QLabel(self.SEM)
        self.label_4.setGeometry(QtCore.QRect(220, 30, 41, 16))
        self.label_4.setObjectName("label_4")
        self.comboBox_quadrant = QtWidgets.QComboBox(self.SEM)
        self.comboBox_quadrant.setGeometry(QtCore.QRect(220, 100, 73, 22))
        self.comboBox_quadrant.setObjectName("comboBox_quadrant")
        self.comboBox_quadrant.addItem("")
        self.comboBox_quadrant.addItem("")
        self.comboBox_quadrant.addItem("")
        self.comboBox_quadrant.addItem("")
        self.label_8 = QtWidgets.QLabel(self.SEM)
        self.label_8.setGeometry(QtCore.QRect(220, 80, 61, 16))
        self.label_8.setObjectName("label_8")
        self.pushButton_move_stage = QtWidgets.QPushButton(self.SEM)
        self.pushButton_move_stage.setGeometry(QtCore.QRect(10, 410, 101, 31))
        self.pushButton_move_stage.setObjectName("pushButton_move_stage")
        self.doubleSpinBox_stage_z = QtWidgets.QDoubleSpinBox(self.SEM)
        self.doubleSpinBox_stage_z.setGeometry(QtCore.QRect(25, 288, 80, 22))
        self.doubleSpinBox_stage_z.setMinimum(-100000.0)
        self.doubleSpinBox_stage_z.setMaximum(100000.0)
        self.doubleSpinBox_stage_z.setObjectName("doubleSpinBox_stage_z")
        self.doubleSpinBox_stage_t = QtWidgets.QDoubleSpinBox(self.SEM)
        self.doubleSpinBox_stage_t.setGeometry(QtCore.QRect(25, 348, 80, 22))
        self.doubleSpinBox_stage_t.setMinimum(-100000.0)
        self.doubleSpinBox_stage_t.setMaximum(360.0)
        self.doubleSpinBox_stage_t.setObjectName("doubleSpinBox_stage_t")
        self.label_26 = QtWidgets.QLabel(self.SEM)
        self.label_26.setGeometry(QtCore.QRect(10, 320, 21, 16))
        self.label_26.setObjectName("label_26")
        self.doubleSpinBox_stage_y = QtWidgets.QDoubleSpinBox(self.SEM)
        self.doubleSpinBox_stage_y.setGeometry(QtCore.QRect(25, 258, 80, 22))
        self.doubleSpinBox_stage_y.setMinimum(-100000.0)
        self.doubleSpinBox_stage_y.setMaximum(100000.0)
        self.doubleSpinBox_stage_y.setProperty("value", 0.0)
        self.doubleSpinBox_stage_y.setObjectName("doubleSpinBox_stage_y")
        self.doubleSpinBox_stage_x = QtWidgets.QDoubleSpinBox(self.SEM)
        self.doubleSpinBox_stage_x.setGeometry(QtCore.QRect(25, 230, 80, 22))
        self.doubleSpinBox_stage_x.setMinimum(-100000.0)
        self.doubleSpinBox_stage_x.setMaximum(100000.0)
        self.doubleSpinBox_stage_x.setObjectName("doubleSpinBox_stage_x")
        self.label_25 = QtWidgets.QLabel(self.SEM)
        self.label_25.setGeometry(QtCore.QRect(10, 290, 21, 16))
        self.label_25.setObjectName("label_25")
        self.label_27 = QtWidgets.QLabel(self.SEM)
        self.label_27.setGeometry(QtCore.QRect(10, 350, 21, 16))
        self.label_27.setObjectName("label_27")
        self.label_23 = QtWidgets.QLabel(self.SEM)
        self.label_23.setGeometry(QtCore.QRect(10, 232, 21, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.SEM)
        self.label_24.setGeometry(QtCore.QRect(10, 260, 21, 16))
        self.label_24.setObjectName("label_24")
        self.doubleSpinBox_stage_r = QtWidgets.QDoubleSpinBox(self.SEM)
        self.doubleSpinBox_stage_r.setGeometry(QtCore.QRect(25, 318, 80, 22))
        self.doubleSpinBox_stage_r.setMinimum(-100000.0)
        self.doubleSpinBox_stage_r.setMaximum(100000.0)
        self.doubleSpinBox_stage_r.setObjectName("doubleSpinBox_stage_r")
        self.pushButton_update_stage_position = QtWidgets.QPushButton(self.SEM)
        self.pushButton_update_stage_position.setGeometry(QtCore.QRect(10, 380, 101, 24))
        self.pushButton_update_stage_position.setObjectName("pushButton_update_stage_position")
        self.comboBox_move_type = QtWidgets.QComboBox(self.SEM)
        self.comboBox_move_type.setGeometry(QtCore.QRect(10, 200, 131, 22))
        self.comboBox_move_type.setObjectName("comboBox_move_type")
        self.comboBox_move_type.addItem("")
        self.comboBox_move_type.addItem("")
        self.comboBox_move_type.addItem("")
        self.checkBox_compucentric = QtWidgets.QCheckBox(self.SEM)
        self.checkBox_compucentric.setGeometry(QtCore.QRect(10, 450, 111, 20))
        self.checkBox_compucentric.setChecked(True)
        self.checkBox_compucentric.setObjectName("checkBox_compucentric")
        self.label_9 = QtWidgets.QLabel(self.SEM)
        self.label_9.setGeometry(QtCore.QRect(110, 350, 31, 16))
        self.label_9.setObjectName("label_9")
        self.label_35 = QtWidgets.QLabel(self.SEM)
        self.label_35.setGeometry(QtCore.QRect(110, 320, 31, 16))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.SEM)
        self.label_36.setGeometry(QtCore.QRect(110, 290, 31, 16))
        self.label_36.setObjectName("label_36")
        self.label_49 = QtWidgets.QLabel(self.SEM)
        self.label_49.setGeometry(QtCore.QRect(110, 260, 31, 16))
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.SEM)
        self.label_50.setGeometry(QtCore.QRect(110, 230, 31, 16))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.SEM)
        self.label_51.setGeometry(QtCore.QRect(175, 198, 81, 16))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.SEM)
        self.label_52.setGeometry(QtCore.QRect(260, 220, 31, 16))
        self.label_52.setObjectName("label_52")
        self.doubleSpinBox_scan_rotation = QtWidgets.QDoubleSpinBox(self.SEM)
        self.doubleSpinBox_scan_rotation.setGeometry(QtCore.QRect(175, 218, 80, 22))
        self.doubleSpinBox_scan_rotation.setMinimum(-100000.0)
        self.doubleSpinBox_scan_rotation.setMaximum(100000.0)
        self.doubleSpinBox_scan_rotation.setObjectName("doubleSpinBox_scan_rotation")
        self.pushButton_set_scan_rotation = QtWidgets.QPushButton(self.SEM)
        self.pushButton_set_scan_rotation.setGeometry(QtCore.QRect(170, 240, 131, 31))
        self.pushButton_set_scan_rotation.setObjectName("pushButton_set_scan_rotation")
        self.tabWidget.addTab(self.SEM, "")
        self.Scans = QtWidgets.QWidget()
        self.Scans.setObjectName("Scans")
        self.pushButton_abort_stack_collection = QtWidgets.QPushButton(self.Scans)
        self.pushButton_abort_stack_collection.setGeometry(QtCore.QRect(270, 330, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.pushButton_abort_stack_collection.setFont(font)
        self.pushButton_abort_stack_collection.setObjectName("pushButton_abort_stack_collection")
        self.label_6 = QtWidgets.QLabel(self.Scans)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.plainTextEdit_sample_name = QtWidgets.QPlainTextEdit(self.Scans)
        self.plainTextEdit_sample_name.setGeometry(QtCore.QRect(100, 10, 291, 31))
        self.plainTextEdit_sample_name.setObjectName("plainTextEdit_sample_name")
        self.pushButton_collect_stack = QtWidgets.QPushButton(self.Scans)
        self.pushButton_collect_stack.setGeometry(QtCore.QRect(140, 330, 101, 28))
        self.pushButton_collect_stack.setObjectName("pushButton_collect_stack")
        self.label_5 = QtWidgets.QLabel(self.Scans)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_5.setObjectName("label_5")
        self.label_53 = QtWidgets.QLabel(self.Scans)
        self.label_53.setGeometry(QtCore.QRect(150, 70, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.doubleSpinBox_x_range = QtWidgets.QDoubleSpinBox(self.Scans)
        self.doubleSpinBox_x_range.setGeometry(QtCore.QRect(10, 90, 91, 22))
        self.doubleSpinBox_x_range.setMaximum(100000000.0)
        self.doubleSpinBox_x_range.setProperty("value", 100.0)
        self.doubleSpinBox_x_range.setObjectName("doubleSpinBox_x_range")
        self.doubleSpinBox_x_step = QtWidgets.QDoubleSpinBox(self.Scans)
        self.doubleSpinBox_x_step.setGeometry(QtCore.QRect(150, 90, 91, 22))
        self.doubleSpinBox_x_step.setMaximum(100000000.0)
        self.doubleSpinBox_x_step.setProperty("value", 2.5)
        self.doubleSpinBox_x_step.setObjectName("doubleSpinBox_x_step")
        self.label_54 = QtWidgets.QLabel(self.Scans)
        self.label_54.setGeometry(QtCore.QRect(340, 70, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.spinBox_Nx = QtWidgets.QSpinBox(self.Scans)
        self.spinBox_Nx.setGeometry(QtCore.QRect(280, 90, 81, 22))
        self.spinBox_Nx.setMaximum(1000000)
        self.spinBox_Nx.setObjectName("spinBox_Nx")
        self.doubleSpinBox_y_step = QtWidgets.QDoubleSpinBox(self.Scans)
        self.doubleSpinBox_y_step.setGeometry(QtCore.QRect(150, 140, 91, 22))
        self.doubleSpinBox_y_step.setMaximum(100000000.0)
        self.doubleSpinBox_y_step.setProperty("value", 2.0)
        self.doubleSpinBox_y_step.setObjectName("doubleSpinBox_y_step")
        self.doubleSpinBox_y_range = QtWidgets.QDoubleSpinBox(self.Scans)
        self.doubleSpinBox_y_range.setGeometry(QtCore.QRect(10, 140, 91, 22))
        self.doubleSpinBox_y_range.setMaximum(100000000.0)
        self.doubleSpinBox_y_range.setProperty("value", 100.0)
        self.doubleSpinBox_y_range.setObjectName("doubleSpinBox_y_range")
        self.label_55 = QtWidgets.QLabel(self.Scans)
        self.label_55.setGeometry(QtCore.QRect(340, 120, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.Scans)
        self.label_56.setGeometry(QtCore.QRect(150, 120, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.Scans)
        self.label_57.setGeometry(QtCore.QRect(10, 120, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.spinBox_Ny = QtWidgets.QSpinBox(self.Scans)
        self.spinBox_Ny.setGeometry(QtCore.QRect(280, 140, 81, 22))
        self.spinBox_Ny.setMaximum(1000000)
        self.spinBox_Ny.setObjectName("spinBox_Ny")
        self.doubleSpinBox_z_step = QtWidgets.QDoubleSpinBox(self.Scans)
        self.doubleSpinBox_z_step.setGeometry(QtCore.QRect(150, 190, 91, 22))
        self.doubleSpinBox_z_step.setMaximum(100000000.0)
        self.doubleSpinBox_z_step.setProperty("value", 12.0)
        self.doubleSpinBox_z_step.setObjectName("doubleSpinBox_z_step")
        self.doubleSpinBox_z_range = QtWidgets.QDoubleSpinBox(self.Scans)
        self.doubleSpinBox_z_range.setGeometry(QtCore.QRect(10, 190, 91, 22))
        self.doubleSpinBox_z_range.setMaximum(100000000.0)
        self.doubleSpinBox_z_range.setProperty("value", 100.0)
        self.doubleSpinBox_z_range.setObjectName("doubleSpinBox_z_range")
        self.label_58 = QtWidgets.QLabel(self.Scans)
        self.label_58.setGeometry(QtCore.QRect(340, 170, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.Scans)
        self.label_59.setGeometry(QtCore.QRect(150, 170, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.Scans)
        self.label_60.setGeometry(QtCore.QRect(10, 170, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.spinBox_Nz = QtWidgets.QSpinBox(self.Scans)
        self.spinBox_Nz.setGeometry(QtCore.QRect(280, 190, 81, 22))
        self.spinBox_Nz.setMaximum(1000000)
        self.spinBox_Nz.setObjectName("spinBox_Nz")
        self.doubleSpinBox_t_step = QtWidgets.QDoubleSpinBox(self.Scans)
        self.doubleSpinBox_t_step.setGeometry(QtCore.QRect(150, 240, 91, 22))
        self.doubleSpinBox_t_step.setMaximum(100000000.0)
        self.doubleSpinBox_t_step.setProperty("value", 0.5)
        self.doubleSpinBox_t_step.setObjectName("doubleSpinBox_t_step")
        self.spinBox_Nt = QtWidgets.QSpinBox(self.Scans)
        self.spinBox_Nt.setGeometry(QtCore.QRect(280, 240, 81, 22))
        self.spinBox_Nt.setMaximum(1000000)
        self.spinBox_Nt.setObjectName("spinBox_Nt")
        self.label_61 = QtWidgets.QLabel(self.Scans)
        self.label_61.setGeometry(QtCore.QRect(340, 220, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.Scans)
        self.label_62.setGeometry(QtCore.QRect(150, 220, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.doubleSpinBox_t_range = QtWidgets.QDoubleSpinBox(self.Scans)
        self.doubleSpinBox_t_range.setGeometry(QtCore.QRect(10, 240, 91, 22))
        self.doubleSpinBox_t_range.setMaximum(100000000.0)
        self.doubleSpinBox_t_range.setProperty("value", 45.0)
        self.doubleSpinBox_t_range.setObjectName("doubleSpinBox_t_range")
        self.label_63 = QtWidgets.QLabel(self.Scans)
        self.label_63.setGeometry(QtCore.QRect(0, 220, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.doubleSpinBox_r_range = QtWidgets.QDoubleSpinBox(self.Scans)
        self.doubleSpinBox_r_range.setGeometry(QtCore.QRect(10, 290, 91, 22))
        self.doubleSpinBox_r_range.setMaximum(100000000.0)
        self.doubleSpinBox_r_range.setProperty("value", 180.0)
        self.doubleSpinBox_r_range.setObjectName("doubleSpinBox_r_range")
        self.label_64 = QtWidgets.QLabel(self.Scans)
        self.label_64.setGeometry(QtCore.QRect(0, 270, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.spinBox_Nr = QtWidgets.QSpinBox(self.Scans)
        self.spinBox_Nr.setGeometry(QtCore.QRect(280, 290, 81, 22))
        self.spinBox_Nr.setMaximum(1000000)
        self.spinBox_Nr.setObjectName("spinBox_Nr")
        self.label_65 = QtWidgets.QLabel(self.Scans)
        self.label_65.setGeometry(QtCore.QRect(340, 270, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.Scans)
        self.label_66.setGeometry(QtCore.QRect(150, 270, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.doubleSpinBox_r_step = QtWidgets.QDoubleSpinBox(self.Scans)
        self.doubleSpinBox_r_step.setGeometry(QtCore.QRect(150, 290, 91, 22))
        self.doubleSpinBox_r_step.setMaximum(100000000.0)
        self.doubleSpinBox_r_step.setProperty("value", 2.0)
        self.doubleSpinBox_r_step.setObjectName("doubleSpinBox_r_step")
        self.pushButton_estimate_stack_time = QtWidgets.QPushButton(self.Scans)
        self.pushButton_estimate_stack_time.setGeometry(QtCore.QRect(10, 330, 111, 28))
        self.pushButton_estimate_stack_time.setObjectName("pushButton_estimate_stack_time")
        self.checkBox_scan_rotation_correction = QtWidgets.QCheckBox(self.Scans)
        self.checkBox_scan_rotation_correction.setGeometry(QtCore.QRect(120, 370, 211, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_scan_rotation_correction.setFont(font)
        self.checkBox_scan_rotation_correction.setChecked(True)
        self.checkBox_scan_rotation_correction.setObjectName("checkBox_scan_rotation_correction")
        self.checkBox_autocontrast_stack = QtWidgets.QCheckBox(self.Scans)
        self.checkBox_autocontrast_stack.setGeometry(QtCore.QRect(10, 370, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_autocontrast_stack.setFont(font)
        self.checkBox_autocontrast_stack.setChecked(True)
        self.checkBox_autocontrast_stack.setObjectName("checkBox_autocontrast_stack")
        self.label_x = QtWidgets.QLabel(self.Scans)
        self.label_x.setGeometry(QtCore.QRect(280, 70, 81, 20))
        self.label_x.setText("")
        self.label_x.setObjectName("label_x")
        self.label_y = QtWidgets.QLabel(self.Scans)
        self.label_y.setGeometry(QtCore.QRect(280, 120, 81, 20))
        self.label_y.setText("")
        self.label_y.setObjectName("label_y")
        self.label_z = QtWidgets.QLabel(self.Scans)
        self.label_z.setGeometry(QtCore.QRect(280, 170, 81, 20))
        self.label_z.setText("")
        self.label_z.setObjectName("label_z")
        self.label_t = QtWidgets.QLabel(self.Scans)
        self.label_t.setGeometry(QtCore.QRect(280, 220, 81, 20))
        self.label_t.setText("")
        self.label_t.setObjectName("label_t")
        self.label_r = QtWidgets.QLabel(self.Scans)
        self.label_r.setGeometry(QtCore.QRect(280, 270, 81, 20))
        self.label_r.setText("")
        self.label_r.setObjectName("label_r")
        self.tabWidget.addTab(self.Scans, "")
        self.Settings = QtWidgets.QWidget()
        self.Settings.setObjectName("Settings")
        self.spinBox_magnification = QtWidgets.QSpinBox(self.Settings)
        self.spinBox_magnification.setGeometry(QtCore.QRect(110, 80, 80, 22))
        self.spinBox_magnification.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinBox_magnification.setMinimum(0)
        self.spinBox_magnification.setMaximum(1000000)
        self.spinBox_magnification.setObjectName("spinBox_magnification")
        self.label_16 = QtWidgets.QLabel(self.Settings)
        self.label_16.setGeometry(QtCore.QRect(10, 80, 81, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.Settings)
        self.label_17.setGeometry(QtCore.QRect(10, 110, 101, 21))
        self.label_17.setObjectName("label_17")
        self.doubleSpinBox_high_voltage = QtWidgets.QDoubleSpinBox(self.Settings)
        self.doubleSpinBox_high_voltage.setGeometry(QtCore.QRect(110, 110, 80, 22))
        self.doubleSpinBox_high_voltage.setMaximum(30.0)
        self.doubleSpinBox_high_voltage.setObjectName("doubleSpinBox_high_voltage")
        self.doubleSpinBox_working_distance = QtWidgets.QDoubleSpinBox(self.Settings)
        self.doubleSpinBox_working_distance.setGeometry(QtCore.QRect(110, 170, 80, 22))
        self.doubleSpinBox_working_distance.setObjectName("doubleSpinBox_working_distance")
        self.label_18 = QtWidgets.QLabel(self.Settings)
        self.label_18.setGeometry(QtCore.QRect(10, 170, 101, 16))
        self.label_18.setObjectName("label_18")
        self.doubleSpinBox_brightness = QtWidgets.QDoubleSpinBox(self.Settings)
        self.doubleSpinBox_brightness.setGeometry(QtCore.QRect(110, 200, 80, 22))
        self.doubleSpinBox_brightness.setMaximum(100.0)
        self.doubleSpinBox_brightness.setObjectName("doubleSpinBox_brightness")
        self.label_19 = QtWidgets.QLabel(self.Settings)
        self.label_19.setGeometry(QtCore.QRect(10, 200, 101, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.Settings)
        self.label_20.setGeometry(QtCore.QRect(10, 230, 101, 16))
        self.label_20.setObjectName("label_20")
        self.doubleSpinBox_contrast = QtWidgets.QDoubleSpinBox(self.Settings)
        self.doubleSpinBox_contrast.setGeometry(QtCore.QRect(110, 230, 80, 22))
        self.doubleSpinBox_contrast.setMaximum(100.0)
        self.doubleSpinBox_contrast.setObjectName("doubleSpinBox_contrast")
        self.label_21 = QtWidgets.QLabel(self.Settings)
        self.label_21.setGeometry(QtCore.QRect(10, 140, 101, 16))
        self.label_21.setObjectName("label_21")
        self.doubleSpinBox_beam_current = QtWidgets.QDoubleSpinBox(self.Settings)
        self.doubleSpinBox_beam_current.setGeometry(QtCore.QRect(110, 140, 80, 22))
        self.doubleSpinBox_beam_current.setObjectName("doubleSpinBox_beam_current")
        self.pushButton_update_SEM_state = QtWidgets.QPushButton(self.Settings)
        self.pushButton_update_SEM_state.setGeometry(QtCore.QRect(10, 330, 181, 24))
        self.pushButton_update_SEM_state.setObjectName("pushButton_update_SEM_state")
        self.label_32 = QtWidgets.QLabel(self.Settings)
        self.label_32.setGeometry(QtCore.QRect(290, 20, 51, 16))
        self.label_32.setObjectName("label_32")
        self.spinBox_average = QtWidgets.QSpinBox(self.Settings)
        self.spinBox_average.setGeometry(QtCore.QRect(340, 18, 71, 22))
        self.spinBox_average.setMinimum(1)
        self.spinBox_average.setMaximum(8000)
        self.spinBox_average.setObjectName("spinBox_average")
        self.label_29 = QtWidgets.QLabel(self.Settings)
        self.label_29.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.label_29.setObjectName("label_29")
        self.comboBox_bit_depth = QtWidgets.QComboBox(self.Settings)
        self.comboBox_bit_depth.setGeometry(QtCore.QRect(70, 17, 61, 22))
        self.comboBox_bit_depth.setObjectName("comboBox_bit_depth")
        self.comboBox_bit_depth.addItem("")
        self.comboBox_bit_depth.addItem("")
        self.label_14 = QtWidgets.QLabel(self.Settings)
        self.label_14.setGeometry(QtCore.QRect(10, 480, 55, 31))
        self.label_14.setObjectName("label_14")
        self.pushButton_initialise_microscope = QtWidgets.QPushButton(self.Settings)
        self.pushButton_initialise_microscope.setGeometry(QtCore.QRect(190, 480, 141, 31))
        self.pushButton_initialise_microscope.setObjectName("pushButton_initialise_microscope")
        self.lineEdit_ip_address = QtWidgets.QLineEdit(self.Settings)
        self.lineEdit_ip_address.setGeometry(QtCore.QRect(70, 480, 111, 31))
        self.lineEdit_ip_address.setObjectName("lineEdit_ip_address")
        self.doubleSpinBox_beam_shift_x = QtWidgets.QDoubleSpinBox(self.Settings)
        self.doubleSpinBox_beam_shift_x.setGeometry(QtCore.QRect(110, 260, 80, 22))
        self.doubleSpinBox_beam_shift_x.setMinimum(-1000.0)
        self.doubleSpinBox_beam_shift_x.setMaximum(1000.0)
        self.doubleSpinBox_beam_shift_x.setObjectName("doubleSpinBox_beam_shift_x")
        self.label_22 = QtWidgets.QLabel(self.Settings)
        self.label_22.setGeometry(QtCore.QRect(10, 260, 101, 16))
        self.label_22.setObjectName("label_22")
        self.doubleSpinBox_beam_shift_y = QtWidgets.QDoubleSpinBox(self.Settings)
        self.doubleSpinBox_beam_shift_y.setGeometry(QtCore.QRect(110, 290, 80, 22))
        self.doubleSpinBox_beam_shift_y.setMinimum(-1000.0)
        self.doubleSpinBox_beam_shift_y.setMaximum(1000.0)
        self.doubleSpinBox_beam_shift_y.setObjectName("doubleSpinBox_beam_shift_y")
        self.label_30 = QtWidgets.QLabel(self.Settings)
        self.label_30.setGeometry(QtCore.QRect(10, 290, 101, 16))
        self.label_30.setObjectName("label_30")
        self.tabWidget.addTab(self.Settings, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_set_EBSD_detector = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_set_EBSD_detector.setGeometry(QtCore.QRect(180, 150, 121, 28))
        self.pushButton_set_EBSD_detector.setObjectName("pushButton_set_EBSD_detector")
        self.spinBox_chip_pixels_x = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_chip_pixels_x.setGeometry(QtCore.QRect(50, 38, 61, 22))
        self.spinBox_chip_pixels_x.setMaximum(5000)
        self.spinBox_chip_pixels_x.setProperty("value", 256)
        self.spinBox_chip_pixels_x.setObjectName("spinBox_chip_pixels_x")
        self.doubleSpinBox_pc_x = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_pc_x.setGeometry(QtCore.QRect(30, 75, 62, 22))
        self.doubleSpinBox_pc_x.setDecimals(3)
        self.doubleSpinBox_pc_x.setProperty("value", 0.421)
        self.doubleSpinBox_pc_x.setObjectName("doubleSpinBox_pc_x")
        self.doubleSpinBox_sample_tilt = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_sample_tilt.setGeometry(QtCore.QRect(190, 120, 71, 22))
        self.doubleSpinBox_sample_tilt.setProperty("value", 70.0)
        self.doubleSpinBox_sample_tilt.setObjectName("doubleSpinBox_sample_tilt")
        self.label_46 = QtWidgets.QLabel(self.tab_3)
        self.label_46.setGeometry(QtCore.QRect(25, 120, 41, 16))
        self.label_46.setObjectName("label_46")
        self.doubleSpinBox_pc_y = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_pc_y.setGeometry(QtCore.QRect(110, 75, 62, 22))
        self.doubleSpinBox_pc_y.setDecimals(3)
        self.doubleSpinBox_pc_y.setProperty("value", 0.779)
        self.doubleSpinBox_pc_y.setObjectName("doubleSpinBox_pc_y")
        self.label_43 = QtWidgets.QLabel(self.tab_3)
        self.label_43.setGeometry(QtCore.QRect(30, 55, 201, 20))
        self.label_43.setObjectName("label_43")
        self.label_48 = QtWidgets.QLabel(self.tab_3)
        self.label_48.setGeometry(QtCore.QRect(30, 152, 71, 16))
        self.label_48.setObjectName("label_48")
        self.label_42 = QtWidgets.QLabel(self.tab_3)
        self.label_42.setGeometry(QtCore.QRect(70, 20, 111, 16))
        self.label_42.setObjectName("label_42")
        self.spinBox_chip_pixels_y = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_chip_pixels_y.setGeometry(QtCore.QRect(140, 38, 61, 22))
        self.spinBox_chip_pixels_y.setMaximum(5000)
        self.spinBox_chip_pixels_y.setProperty("value", 256)
        self.spinBox_chip_pixels_y.setObjectName("spinBox_chip_pixels_y")
        self.doubleSpinBox_detector_pixel_size = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_detector_pixel_size.setGeometry(QtCore.QRect(100, 100, 71, 22))
        self.doubleSpinBox_detector_pixel_size.setProperty("value", 55.0)
        self.doubleSpinBox_detector_pixel_size.setObjectName("doubleSpinBox_detector_pixel_size")
        self.doubleSpinBox_pc_z = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_pc_z.setGeometry(QtCore.QRect(190, 75, 62, 22))
        self.doubleSpinBox_pc_z.setDecimals(3)
        self.doubleSpinBox_pc_z.setProperty("value", 0.505)
        self.doubleSpinBox_pc_z.setObjectName("doubleSpinBox_pc_z")
        self.doubleSpinBox_detector_tilt = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_detector_tilt.setGeometry(QtCore.QRect(40, 120, 71, 22))
        self.doubleSpinBox_detector_tilt.setProperty("value", 0.0)
        self.doubleSpinBox_detector_tilt.setObjectName("doubleSpinBox_detector_tilt")
        self.label_44 = QtWidgets.QLabel(self.tab_3)
        self.label_44.setGeometry(QtCore.QRect(180, 102, 51, 16))
        self.label_44.setObjectName("label_44")
        self.label_41 = QtWidgets.QLabel(self.tab_3)
        self.label_41.setGeometry(QtCore.QRect(120, 38, 20, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_47 = QtWidgets.QLabel(self.tab_3)
        self.label_47.setGeometry(QtCore.QRect(120, 124, 71, 16))
        self.label_47.setObjectName("label_47")
        self.label_45 = QtWidgets.QLabel(self.tab_3)
        self.label_45.setGeometry(QtCore.QRect(20, 102, 81, 16))
        self.label_45.setObjectName("label_45")
        self.spinBox_binning = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_binning.setGeometry(QtCore.QRect(225, 100, 41, 22))
        self.spinBox_binning.setMinimum(1)
        self.spinBox_binning.setMaximum(100000)
        self.spinBox_binning.setProperty("value", 1)
        self.spinBox_binning.setObjectName("spinBox_binning")
        self.comboBox_convention = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_convention.setGeometry(QtCore.QRect(100, 152, 73, 21))
        self.comboBox_convention.setObjectName("comboBox_convention")
        self.comboBox_convention.addItem("")
        self.comboBox_convention.addItem("")
        self.checkBox_remove_dynamic_background = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_remove_dynamic_background.setGeometry(QtCore.QRect(20, 280, 191, 20))
        self.checkBox_remove_dynamic_background.setObjectName("checkBox_remove_dynamic_background")
        self.pushButton_open_stack = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_open_stack.setGeometry(QtCore.QRect(20, 230, 131, 28))
        self.pushButton_open_stack.setObjectName("pushButton_open_stack")
        self.checkBox_remove_static_background = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_remove_static_background.setGeometry(QtCore.QRect(20, 260, 181, 20))
        self.checkBox_remove_static_background.setObjectName("checkBox_remove_static_background")
        self.label_38 = QtWidgets.QLabel(self.tab_3)
        self.label_38.setGeometry(QtCore.QRect(40, 440, 101, 16))
        self.label_38.setObjectName("label_38")
        self.label_40 = QtWidgets.QLabel(self.tab_3)
        self.label_40.setGeometry(QtCore.QRect(160, 450, 31, 16))
        self.label_40.setObjectName("label_40")
        self.label_39 = QtWidgets.QLabel(self.tab_3)
        self.label_39.setGeometry(QtCore.QRect(160, 430, 31, 16))
        self.label_39.setObjectName("label_39")
        self.spinBox_y0 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_y0.setGeometry(QtCore.QRect(180, 450, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_y0.setFont(font)
        self.spinBox_y0.setMaximum(5000)
        self.spinBox_y0.setObjectName("spinBox_y0")
        self.spinBox_x0 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_x0.setGeometry(QtCore.QRect(180, 430, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_x0.setFont(font)
        self.spinBox_x0.setMaximum(5000)
        self.spinBox_x0.setObjectName("spinBox_x0")
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout.addWidget(self.frame_1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_image_frame1 = QtWidgets.QLabel(self.frame)
        self.label_image_frame1.setGeometry(QtCore.QRect(0, 20, 768, 512))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image_frame1.sizePolicy().hasHeightForWidth())
        self.label_image_frame1.setSizePolicy(sizePolicy)
        self.label_image_frame1.setMinimumSize(QtCore.QSize(256, 256))
        self.label_image_frame1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image_frame1.setText("")
        self.label_image_frame1.setObjectName("label_image_frame1")
        self.label_measurement_type1 = QtWidgets.QLabel(self.frame)
        self.label_measurement_type1.setGeometry(QtCore.QRect(10, 0, 55, 16))
        self.label_measurement_type1.setObjectName("label_measurement_type1")
        self.label_counter = QtWidgets.QLabel(self.frame)
        self.label_counter.setGeometry(QtCore.QRect(720, 610, 81, 31))
        self.label_counter.setText("")
        self.label_counter.setObjectName("label_counter")
        self.label_demo_mode = QtWidgets.QLabel(self.frame)
        self.label_demo_mode.setGeometry(QtCore.QRect(560, 590, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_demo_mode.setFont(font)
        self.label_demo_mode.setText("")
        self.label_demo_mode.setWordWrap(True)
        self.label_demo_mode.setObjectName("label_demo_mode")
        self.comboBox_image_convention = QtWidgets.QComboBox(self.frame)
        self.comboBox_image_convention.setGeometry(QtCore.QRect(630, 550, 131, 22))
        self.comboBox_image_convention.setObjectName("comboBox_image_convention")
        self.comboBox_image_convention.addItem("")
        self.comboBox_image_convention.addItem("")
        self.comboBox_image_convention.addItem("")
        self.doubleSpinBox_point_x = QtWidgets.QDoubleSpinBox(self.frame)
        self.doubleSpinBox_point_x.setGeometry(QtCore.QRect(100, 580, 121, 22))
        self.doubleSpinBox_point_x.setMinimum(-1000000.0)
        self.doubleSpinBox_point_x.setMaximum(1000000.0)
        self.doubleSpinBox_point_x.setObjectName("doubleSpinBox_point_x")
        self.doubleSpinBox_point_y = QtWidgets.QDoubleSpinBox(self.frame)
        self.doubleSpinBox_point_y.setGeometry(QtCore.QRect(240, 580, 121, 22))
        self.doubleSpinBox_point_y.setMinimum(-1000000.0)
        self.doubleSpinBox_point_y.setMaximum(1000000.0)
        self.doubleSpinBox_point_y.setObjectName("doubleSpinBox_point_y")
        self.label_34 = QtWidgets.QLabel(self.frame)
        self.label_34.setGeometry(QtCore.QRect(10, 575, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(740, 580, 20, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton_correlation = QtWidgets.QPushButton(self.frame)
        self.pushButton_correlation.setGeometry(QtCore.QRect(400, 580, 131, 28))
        self.pushButton_correlation.setObjectName("pushButton_correlation")
        self.pushButton_open_file = QtWidgets.QPushButton(self.frame)
        self.pushButton_open_file.setGeometry(QtCore.QRect(530, 550, 93, 25))
        self.pushButton_open_file.setObjectName("pushButton_open_file")
        self.doubleSpinBox_pixel_size = QtWidgets.QDoubleSpinBox(self.frame)
        self.doubleSpinBox_pixel_size.setGeometry(QtCore.QRect(75, 540, 101, 22))
        self.doubleSpinBox_pixel_size.setMinimum(0.0)
        self.doubleSpinBox_pixel_size.setMaximum(1000000000.0)
        self.doubleSpinBox_pixel_size.setObjectName("doubleSpinBox_pixel_size")
        self.label_31 = QtWidgets.QLabel(self.frame)
        self.label_31.setGeometry(QtCore.QRect(15, 542, 71, 16))
        self.label_31.setObjectName("label_31")
        self.label_67 = QtWidgets.QLabel(self.frame)
        self.label_67.setGeometry(QtCore.QRect(180, 542, 31, 16))
        self.label_67.setObjectName("label_67")
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1278, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_10.setText(_translate("MainWindow", "messages"))
        self.pushButton_acquire.setText(_translate("MainWindow", "Acquire"))
        self.label_3.setText(_translate("MainWindow", "Horizontal field width, µm"))
        self.comboBox_detector.setItemText(0, _translate("MainWindow", "ETD"))
        self.comboBox_detector.setItemText(1, _translate("MainWindow", "TLD"))
        self.comboBox_detector.setItemText(2, _translate("MainWindow", "ICE"))
        self.label.setText(_translate("MainWindow", "Detector"))
        self.label_2.setText(_translate("MainWindow", "dwell time, µs"))
        self.pushButton_select_directory.setText(_translate("MainWindow", "select directory"))
        self.comboBox_resolution.setItemText(0, _translate("MainWindow", "768x512"))
        self.comboBox_resolution.setItemText(1, _translate("MainWindow", "1536x1024"))
        self.comboBox_resolution.setItemText(2, _translate("MainWindow", "3072x2048"))
        self.comboBox_resolution.setItemText(3, _translate("MainWindow", "6144x4096"))
        self.comboBox_resolution.setItemText(4, _translate("MainWindow", "1024x884"))
        self.comboBox_resolution.setItemText(5, _translate("MainWindow", "2048x1768"))
        self.comboBox_resolution.setItemText(6, _translate("MainWindow", "4096x3536"))
        self.label_28.setText(_translate("MainWindow", "Resolution"))
        self.checkBox_autocontrast.setText(_translate("MainWindow", "autocontrast"))
        self.pushButton_last_image.setText(_translate("MainWindow", "Last image"))
        self.checkBox_save_image.setText(_translate("MainWindow", "save image"))
        self.comboBox_beam_type.setItemText(0, _translate("MainWindow", "Electron"))
        self.comboBox_beam_type.setItemText(1, _translate("MainWindow", "Ion"))
        self.label_4.setText(_translate("MainWindow", "Beam"))
        self.comboBox_quadrant.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_quadrant.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_quadrant.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_quadrant.setItemText(3, _translate("MainWindow", "4"))
        self.label_8.setText(_translate("MainWindow", "Quadrant"))
        self.pushButton_move_stage.setText(_translate("MainWindow", "Move to position"))
        self.label_26.setText(_translate("MainWindow", "R"))
        self.label_25.setText(_translate("MainWindow", "Z"))
        self.label_27.setText(_translate("MainWindow", "T"))
        self.label_23.setText(_translate("MainWindow", "X"))
        self.label_24.setText(_translate("MainWindow", "Y"))
        self.pushButton_update_stage_position.setText(_translate("MainWindow", "Get position"))
        self.comboBox_move_type.setItemText(0, _translate("MainWindow", "Relative"))
        self.comboBox_move_type.setItemText(1, _translate("MainWindow", "Absolute"))
        self.comboBox_move_type.setItemText(2, _translate("MainWindow", "Raw coordinates"))
        self.checkBox_compucentric.setText(_translate("MainWindow", "compucentric"))
        self.label_9.setText(_translate("MainWindow", "deg"))
        self.label_35.setText(_translate("MainWindow", "deg"))
        self.label_36.setText(_translate("MainWindow", "µm"))
        self.label_49.setText(_translate("MainWindow", "µm"))
        self.label_50.setText(_translate("MainWindow", "µm"))
        self.label_51.setText(_translate("MainWindow", "Scan rotation"))
        self.label_52.setText(_translate("MainWindow", "deg"))
        self.pushButton_set_scan_rotation.setText(_translate("MainWindow", "Set scan rotation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SEM), _translate("MainWindow", "SEM"))
        self.pushButton_abort_stack_collection.setText(_translate("MainWindow", "Abort"))
        self.label_6.setText(_translate("MainWindow", "+/- x range, µm"))
        self.plainTextEdit_sample_name.setPlainText(_translate("MainWindow", "sample_name"))
        self.pushButton_collect_stack.setText(_translate("MainWindow", "collect stack"))
        self.label_5.setText(_translate("MainWindow", "Sample name:"))
        self.label_53.setText(_translate("MainWindow", "step  ∆x, µm"))
        self.label_54.setText(_translate("MainWindow", "Nx"))
        self.label_55.setText(_translate("MainWindow", "Ny"))
        self.label_56.setText(_translate("MainWindow", "step  ∆y, µm"))
        self.label_57.setText(_translate("MainWindow", "+/- y range, µm"))
        self.label_58.setText(_translate("MainWindow", "Nz"))
        self.label_59.setText(_translate("MainWindow", "step  ∆z, µm"))
        self.label_60.setText(_translate("MainWindow", "+/- z range, µm"))
        self.label_61.setText(_translate("MainWindow", "Nt"))
        self.label_62.setText(_translate("MainWindow", "step  ∆t, deg"))
        self.label_63.setText(_translate("MainWindow", "t range, deg, 0..tmax"))
        self.label_64.setText(_translate("MainWindow", "r range, deg, 0..rmax"))
        self.label_65.setText(_translate("MainWindow", "Nr"))
        self.label_66.setText(_translate("MainWindow", "step  ∆r, deg"))
        self.pushButton_estimate_stack_time.setText(_translate("MainWindow", "estimate time"))
        self.checkBox_scan_rotation_correction.setText(_translate("MainWindow", "correct with scan rotation"))
        self.checkBox_autocontrast_stack.setText(_translate("MainWindow", "autocontrast"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Scans), _translate("MainWindow", "Scans"))
        self.label_16.setText(_translate("MainWindow", "Magnification"))
        self.label_17.setText(_translate("MainWindow", "High voltage V"))
        self.label_18.setText(_translate("MainWindow", "WD mm"))
        self.label_19.setText(_translate("MainWindow", "Brightness %"))
        self.label_20.setText(_translate("MainWindow", "Contrast %"))
        self.label_21.setText(_translate("MainWindow", "Beam current nA"))
        self.pushButton_update_SEM_state.setText(_translate("MainWindow", "Update SEM state"))
        self.label_32.setText(_translate("MainWindow", "Average"))
        self.label_29.setText(_translate("MainWindow", "Bit depth"))
        self.comboBox_bit_depth.setItemText(0, _translate("MainWindow", "8"))
        self.comboBox_bit_depth.setItemText(1, _translate("MainWindow", "16"))
        self.label_14.setText(_translate("MainWindow", "ip adress"))
        self.pushButton_initialise_microscope.setText(_translate("MainWindow", "Initialise microscope"))
        self.lineEdit_ip_address.setText(_translate("MainWindow", "192.168.0.1"))
        self.label_22.setText(_translate("MainWindow", "Beam shift x"))
        self.label_30.setText(_translate("MainWindow", "Beam shift y"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Settings), _translate("MainWindow", "Settings"))
        self.pushButton_set_EBSD_detector.setText(_translate("MainWindow", "Set EBSD detector"))
        self.label_46.setText(_translate("MainWindow", "tilt"))
        self.label_43.setText(_translate("MainWindow", "Pattern centre (pc_x, pc_y, pc_z)"))
        self.label_48.setText(_translate("MainWindow", "convention"))
        self.label_42.setText(_translate("MainWindow", "Detector chip size"))
        self.label_44.setText(_translate("MainWindow", "Binning"))
        self.label_41.setText(_translate("MainWindow", "×"))
        self.label_47.setText(_translate("MainWindow", "sample tilt"))
        self.label_45.setText(_translate("MainWindow", "pixel size, um"))
        self.comboBox_convention.setItemText(0, _translate("MainWindow", "tsl"))
        self.comboBox_convention.setItemText(1, _translate("MainWindow", "bruker"))
        self.checkBox_remove_dynamic_background.setText(_translate("MainWindow", "remove dynamic background"))
        self.pushButton_open_stack.setText(_translate("MainWindow", "Open stack"))
        self.checkBox_remove_static_background.setText(_translate("MainWindow", "remove static background"))
        self.label_38.setText(_translate("MainWindow", "Start point, pixels"))
        self.label_40.setText(_translate("MainWindow", "y0"))
        self.label_39.setText(_translate("MainWindow", "x0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "---"))
        self.label_measurement_type1.setText(_translate("MainWindow", "SEM"))
        self.comboBox_image_convention.setItemText(0, _translate("MainWindow", "Raw data"))
        self.comboBox_image_convention.setItemText(1, _translate("MainWindow", "EBSD convention"))
        self.comboBox_image_convention.setItemText(2, _translate("MainWindow", "TEM convention"))
        self.label_34.setText(_translate("MainWindow", "selected point"))
        self.label_7.setText(_translate("MainWindow", "×"))
        self.pushButton_correlation.setText(_translate("MainWindow", "correlation test"))
        self.pushButton_open_file.setText(_translate("MainWindow", "Open file"))
        self.label_31.setText(_translate("MainWindow", "pixel size"))
        self.label_67.setText(_translate("MainWindow", "nm"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

